### PR TITLE
Create tox.ini and ci.yml to update fitsblender package

### PR DESCRIPTION
**Pull request by mdlpstsci**
A tox.ini and ci.yml file were created for this package based upon what was done for the "drizzle" and "jwst" packages to update this package.  It was necessary to create a setup.cfg to ignore certain flake8 issues at this time.  However, the blender.py and blendheaders.py modules were modified to correct important flake8 issues.  Finally, the pyproject.toml file was updated to have "build-backend".   This was a learning experience and experienced reviewer comments are welcome.

### CODE REVIEW

**Review by zacharyburnett — APPROVED** [review]
This looks good to me. You can probably rename the `setup.cfg` -> `.flake8`, if you want, as it only contains `flake8` configuration.

Additionally, `setuptools>=60` currently officially supports reading project metadata from `pyproject.toml` (in the `[project]` table) in accordance with PEP621. 

`setuptools` will also (eventually) officially support using the `[tool.setuptools]` table in `pyproject.toml` when Python 3.11 is released. Keeping metadata in `setup.py` and `setup.cfg` is fine for the forseeable future, but I expect that both files will eventually be deprecated as more and more configuration moves to `pyproject.toml`.

Here's an example of using `pyproject.toml` for configuration: https://github.com/spacetelescope/jwst/pull/6847/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Review by stsci-hack — APPROVED** [review]
LGTM

**Comment by mdlpstsci** [comment]
Aside for looking at ci.yml and tox.ini in the _drizzle_ and _jwst_ packages, I also found the following URLs useful for a newbie:
https://github.github.io/actions-cheat-sheet/actions-cheat-sheet.pdf
https://tox.wiki/en/latest/config.html

**Comment by mdlpstsci** [comment]
New associated ticket Jira HLA-820.

**Pull request merged**
